<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>MikoBarrier.Guard</AssemblyName>
    <RootNamespace>MikoBarrier.Guard</RootNamespace>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MikoBarrier.Core\MikoBarrier.Core.csproj" />
  </ItemGroup>

</Project>
