<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>MikoBarrier.Core</AssemblyName>
    <RootNamespace>MikoBarrier.Core</RootNamespace>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
